name: pytest

# The following chooses at which steps this `action`
# should be triggered. 
# If one wants to run this action at very `push` set:
# `on: [push]`
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package with the dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test code coverage
      run: |
        pip install .[tests]
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
